import swaggerAutogen from 'swagger-autogen';

const outputFile = './swagger_output.json';
const endpointsFiles = ['./index.js'];

const doc = {
    info: {
        version: "1.0.0",
        title: "SGS Bacen API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3001",
    basePath: "/",
    schemes: ['http'],
    paths: {},
};

swaggerAutogen()(outputFile, endpointsFiles, doc).then(async () => {
    await import('./index.js'); // Your project's root file
});