import swaggerAutogen from 'swagger-autogen';

const outputFile = './swagger_output.json';
const endpointsFiles = ['./index.js'];

const doc = {
    info: {
        version: "1.0.0",
        title: "SGS Bacen API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    definitions: {
        Metric: {
            code: "226"
        },
        SingleDate: "15/08/2022",
        RangedDate: {
            startDate: "01/03/2022",
            endDate: "01/07/2022"
        }
    },
    host: "localhost:3001",
    basePath: "/",
    schemes: ['http'],
    paths: {},
};

swaggerAutogen({ openapi: '3.0.0' })(outputFile, endpointsFiles, doc);